# Generated by Django 5.2.4 on 2025-12-23 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image', models.URLField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='games', to='games.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteGame',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorite_game', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_users', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_total', models.IntegerField(default=0)),
                ('playtime_recent_2weeks', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(related_name='owned_games', through='games.UserGameLibrary', to=settings.AUTH_USER_MODEL),
        ),
    ]
