# Generated by Django 5.2.4 on 2025-12-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
