# Generated by Django 5.2.4 on 2025-12-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
