# Generated by Django 5.2.4 on 2025-12-24 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
